name: Build And Publish Snapshot
on: pull_request

jobs:
  build:
    name: Build pull request
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xmx2g -Dorg.gradle.daemon=false
    #services:
    #  flow-emulator:
    #    image: gcr.io/flow-container-registry/emulator
    #    env:
    #      FLOW_VERBOSE: true
    #      FLOW_PORT: 3569
    #      FLOW_INTERVAL: 5s
    #      FLOW_PERSIST: false
    #    ports:
    #      - 3569:3569
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '21'
          java-package: jdk

      - name: Install flow emulator
        run: sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew --warning-mode all check build -x test

      - name: Test
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./gradlew --no-daemon --max-workers=2 --warning-mode=all test --continue --stacktrace
        if: "!contains(github.event.head_commit.message, '[i am bad and i hate unit tests]')"

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.18
        if: always()
        with:
          files: "**/test-results/**/*.xml"
